### ISSUE TITLE
[BUG] fvtt-pointer does not respect fvtt routePrefix

### ISSUE THREAD

**Issue by js-murph** [Moerill/fvtt-pointer#1]
**Describe the bug**
The module fails to load when using the routePrefix option on foundry.

**To Reproduce**
1. Enable a routePrefix when starting foundry
2. Open any world with fvtt-pointer enabled

This will result in the following console output:

```
GET https://mydomain/scripts/greensock/esm/all.js net::ERR_ABORTED 404
```

**Expected behavior**
With the routePrefix option enabled I would expect it to fetch the resource as below:

```
GET https://mydomain/myprefix/scripts/greensock/esm/all.js
```

**Module incompatibilities**
This can be reproduced with no other modules active.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - FVTT Version: 0.7.5
 - Module version: 0.2.0

**Comment by Moerill** [comment]
Thanks for the bug report. should be fixed now, please report back if it works now.

**Comment by js-murph** [comment]
Yep, it now works as expected, thank you :)
