### ISSUE TITLE
[BUG] `scale` parameter not honored in ping

### ISSUE THREAD

**Issue by thomasmckay** [Moerill/fvtt-pointer#12]
**Describe the bug**
The `scale` parameter does not alter the displayed graphic.
```
        canvas.controls.pointer.ping({
            userId: user.id,
            position: {
                x: token.x + canvas.grid.w / 2,
                y: token.y + canvas.grid.w / 2
            },
            force: false,
            scale: 4 * canvas.stage.scale.x
        })
```

**To Reproduce**
Call `ping()` with altered scale.

**Expected behavior**
Graphic is scaled.

**Comment by Moerill** [comment]
its working as intended. The parameter is not there for scaling the ping, but for scaling (zooming) the canvas correctly, *if* it is a forced gm ping. (yeye i know its missing documentation...)

**Comment by thomasmckay** [comment]
Noted, thanks!
