### ISSUE TITLE
[FEATURE] Custom Ping

### ISSUE THREAD

**Issue by jenthura** [Moerill/fvtt-pointer#16]
Currently it's possible to set a custom pointer, but not a custom ping. I would love to theme both the ping and the pointer to match my game's UI.

**Comment by Moerill** [comment]
this is already possible:  

![image](https://user-images.githubusercontent.com/26152015/106034378-24669280-60d3-11eb-8e36-ab7186da1480.png)

Just check the box for "ping" instead of "pointer".
