### ISSUE TITLE
[BUG] Foundry (On forge) can't find pointer.svg

### ISSUE THREAD

**Issue by ebrownewell** [Moerill/fvtt-pointer#19]
I've been experiencing a problem where I cannot see the little hand when I hit X to display it. I check my settings and all I see is a big X in the middle of the grid, no pointer. I also see the below error in the console. I'm currently running from the Forge but the files seem to be in the correct place when I click a type of pointer and try to update the image (see second image below)

**Module incompatibilities**
This issue happens even in a fresh world with no other modules installed.

**Screenshots/GIFs/Videos**
console error:
![image](https://user-images.githubusercontent.com/38708687/110024545-423f9c80-7cfc-11eb-8330-2b3dd52dad17.png)

assets folder:
![image](https://user-images.githubusercontent.com/38708687/110025046-e0cbfd80-7cfc-11eb-9055-9c867becdf74.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - FVTT Version 0.7.9
 - Module version 2.3.1

**Comment by Moerill** [comment]
Thanks for the bug report.  
i'm actually not sure what is going wrong here, since the url its searching for is actually (supposed) to be a valid URL. (although its said differently in the error)

Does this error still exist?

**Comment by Maghawk** [comment]
This error is happening for me as well. 
In fact the whole module is acting a little weird for me right now, but yeah the hand specifically seems to be gone.

"foundry.js:36238 Failed to load texture modules/pointer/assets/pointer.svg: Invalid URL"

OS: Mac Catalina
Browser: Chrome
FVTT 0.7.9
Module version 2.3.1

**Comment by Moerill** [comment]
Do i understand it correctly: Its only the hand that is missing for you? 

Could you please check if you can properly access that image in some other way?  
Like.. go to ``your-game.url/modules/pointer/assets/pointer.svg``and look if you can see the image.  
Additonally please create a token using that image and see if it works or not.

**Comment by Maghawk** [comment]
Well now that I decide to make a video of it, it's working in game again... which is good!
In fact all the weird bits have fixed themselves. Haven't updated yet, so unsure what happened, but it was definitely temperamental for the last two sessions. Oh well.

**Comment by Moerill** [comment]
Good to hear!
I'll just close this for the time being then.
If @ebrownewell or someone else still has the error, please test what i posted previously and report back (and i'll reopen this issue)
