### ISSUE TITLE
[BUG] Is this module called "Pointer and Pings!" (module) or "Pings and Pointer" (readme)

### ISSUE THREAD

**Issue by ScottMaclure** [Moerill/fvtt-pointer#21]
Compare:

https://github.com/Moerill/fvtt-pointer/blob/master/module.json

```
"title": "PnP - Pointer and Pings!",
```

with https://raw.githubusercontent.com/Moerill/fvtt-pointer/master/README.md

```
# PnP - Pings and Pointer
```

I found this confusing - had to double-check I had the right module for a second!

Recommend update readme to align with published module name.

**Comment by ScottMaclure** [comment]
Raised PR:
https://github.com/Moerill/fvtt-pointer/pull/22

**Comment by Moerill** [comment]
Thanks. While Pings and Pointer feels bit more natural to me its supposed to be Pointer and Pings - for legacy sake and not to try and take to much fame from the Pings module. (even though its based on the earliest versions of this module^^)

Thanks for the PR
