### ISSUE TITLE
No longer seems to work - module settings don't show in 0.8.9

### ISSUE THREAD

**Issue by tbrockwood** [Moerill/fvtt-pointer#27]
Upgraded to Foundry 0.8.9, and now PnP no longer works. Nothing appears when I hit the hotkey that used to work, and when I go into Foundry's module settings tab to see if I can tweak things, there's no entry for PnP any more. I've removed all other modules to see if that'd help, but nope.

**Comment by windsurfer** [comment]
It's probably an ad filter. It might be blocking the loading of "/ScrollToPlugin.js". Disable your ad-blocking software and it will likely work again.

**Comment by Moerill** [comment]
Hope windsurfers solution fixed this.  

A general fix for v9 was provided by someone, so closing this now.
