### ISSUE TITLE
No longer working in V9

### ISSUE THREAD

**Issue by apoapostolov** [Moerill/fvtt-pointer#29]
The issue seems to be that it doesn't register X in the new Keybindings API

keybindings.js:104 Uncaught TypeError: game.keyboard.getKey is not a function
[Detected 1 package: pointer]
    at checkKey (keybindings.js:104)
    at onPointerDown (keybindings.js:123)
checkKey @ keybindings.js:104
onPointerDown @ keybindings.js:123

However also the Pointer with long press doesn't seem to work.

**Comment by Moerill** [comment]
Thanks for the bug report.  

I'm to busy in the near future to work on my modules. (This counts for all my modules)  
But i'm happy to include any bugfixes or so from PRs. (You may have to ping me or write me on discord at least once to notice them though.)
Or: if someone wants to maintain the module for the time being, i'm happy to work something out with that person.

**Comment by notgithub111** [comment]
I can't get it to accept any input key except right click and left click on from the mouse.
Sadly I don't have any coding skills to help sort it out.

**Comment by spaceotter** [comment]
My players like this mod so I was sad when it didn't work in v9. I've posted a patch that seems to work, but the new keybinding system doesn't allow binding to mouse events.
