### ISSUE TITLE
[BUG] short bug description invisable creature are pingable

### ISSUE THREAD

**Issue by zrampage96** [Moerill/fvtt-pointer#40]
**Describe the bug**
you are able to ping in combat invisable combatints both as a gm and player
Also post console errors (F12 for most browsers) here that occur.

**To Reproduce**
1. start a encounter
2. Click the ping for the creature that is set to be invisable by the condision menu

**Expected behavior**
to be unable to ping invisable combationts as a player to advoid cheating

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome (unknown if it happens on others
 - FVTT Version 10 build 285
 - Module version 2.3.4

**Comment by Moerill** [comment]
This module is about being able to ping *anywhere* on the map, even on unvisited places. (e.g. to show where you want to go),  Clicking on a creature or not doesn't make any difference for how the module behaves (and should behave).  

Therefore, if i understand your issue correctly, this is intended and not a bug. If your players use this to cheat its on them, and quite a pity.  
The only thing that *could* be changed is to show the pointer only in the field of vision of owned tokens, but this would completly defeat the point of this module in my opinion.
