### ISSUE TITLE
[Style] Text in black

### ISSUE THREAD

**Issue by DeathLighT-Jerome** [Moerill/fvtt-pointer#6]
**Describe the bug**
Hi !
I can't use the module, all texts are in black.
See here [pnpblacktext](https://1drv.ms/u/s!Apj3yWGhi-PdjrVjO9OtiJhU--eGJg)

**To Reproduce**
Foundry virtual Tabletop 0.7.6
Warhammer Fantasy Roleplar 4th Edition 3.0.1

**Desktop (please complete the following information):**
- Windows 10 2004
- Goggle Chrome 86 // Firefox 82

**Comment by Moerill** [comment]
you can still use it, its just kinda difficult to set up..

I'd prefer this to be fixed on the wfrp side, since this issue would possibly not only affect this module, so i posted an issue over there (as seen above)
If i don't hear back from them i'll provide a fix from my side for this module...

**Comment by Moerill** [comment]
I fixed it.. i hate it though and it really should be done by wfrp and not by every module themself creating custom apps <_<

**Comment by DeathLighT-Jerome** [comment]
Thank you. After tests, the color came from windows.app. I don't think the wfrp system would proceed on it.
