### ISSUE TITLE
[BUG] PnP somehow breaking/offsetting layers

### ISSUE THREAD

**Issue by LorduFreeman** [Moerill/fvtt-pointer#7]
@DMDicependent#9166 reported this one (ping in Discord for more info)

Versions:
0.7.7 On Foundry
DnD5e System 1.1.1
PnP version 2.3.0

"Changing maps won't work properly, neither will pinging as a whole"
"Another note - with all of my modules enabled excluding PnP, there are no errors on the console, simply warnings"

Error pics:
"Here's what it looks like - when I change map scenes they stack on top of each other."
https://cdn.discordapp.com/attachments/722566083499786352/777318088198062100/Screengrab.PNG
https://cdn.discordapp.com/attachments/722566083499786352/777321485240107008/Screengrab_3.PNG

**Comment by Moerill** [comment]
Tried to debug, and we couldn't really find the reason to. Maybe its a core issue, resulting in PnP failing...? (at least some core issues seem to arise before the PnP issues arise)

**Comment by Moerill** [comment]
Long debugging session and we solved it it seems (and i just forgot to close this issue..)
