### ISSUE TITLE
[FEATURE] Request roll20 type ping (no need to hold down a key to ping)

### ISSUE THREAD

**Issue by Geodragon9** [Moerill/fvtt-pointer#9]
Looking for the option to enable an option or an additional ping where I use left click and hold to create the ping instead of holding down the x and the pressing the left mouse button.

**Comment by Moerill** [comment]
duplicate of https://github.com/Moerill/fvtt-pointer/issues/2

**Comment by Geodragon9** [comment]
Not quite a duplicate.  They wanted long press option for right click alternative for mac track pad.

Nov 15, 2020 14:04:47 Moerill <notifications@github.com>:
